spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/our-data
    username: postgres
    password: AnotherBanger
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true