spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/human_os_data
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgresSQLDialect
  mail:
    host: localhost
    port: 1025
    username: kemh
    password: my-login-password
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: tru
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

  security:
    user:
      name: kemh
      password: my-login-password